alias reload!='. ~/.zshrc'

alias cls='clear' # Good 'ol Clear Screen command
alias y="yarn"
alias g="git"
alias mux="tmuxinator"
alias lzg="lazygit"
alias glz="lazygit"
alias ci="glab ci status -l"
alias t="task"
alias tui="taskwarrior-tui"
alias tt="taskwarrior-tui"
alias to="taskopen"
alias ta="task add"
alias p="pnpm"
alias assume='source $(asdf which assume)'
alias ls="lsd"
alias ll="lsd -l"
alias lla="lsd -la"
alias lstree="lsd -d --tree"
